<?php

/**
 * BaseQuarter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Store
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getStore() Returns the current record's "Store" collection
 * @method Quarter             setName()  Sets the current record's "name" value
 * @method Quarter             setStore() Sets the current record's "Store" collection
 * 
 * @package    mendozaoferta
 * @subpackage model
 * @author     diego@cooperativahormigon.com.ar
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BaseQuarter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quarter');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Store', array(
             'local' => 'id',
             'foreign' => 'quarter_id'));
    }
}