all:
  sf_admin_dash:
    web_dir:                      /sfAdminDashPlugin
    image_dir:                    /sfAdminDashPlugin/images/icons/
    default_image:                config.png
    resize_mode:                  thumbnail
    site:                         Ahorra Seguro
    include_path:                 true
    include_jquery_no_conflict:   false
    logout:                       true
    login_route:                  @sf_guard_signin
    logout_route:                 @sf_guard_signout
    categories:
      Datos:
        items:
          Vendedores:
            url:    seller
            image:        addedit.png
          Comercios:
            url:    store
            image:        addedit.png
          Categorias:
            url:    category
            image:        addedit.png
          Barrios:
            url:    quarter
            image:        addedit.png
          Ofertas:
            url:    deal
            image:        addedit.png
      Usuarios:
        items:
          Usuarios:
            url:          sf_guard_user
            image:        users.png
      Compras:
        items:
          "Compras de Usuarios":
            url:    payment
            image:        addedit.png
          "Consultar Dineromail":
            url:    dineromail_pays
      Newsletter:
        items:
          Suscriptos:
            url:    newsletter_email            
          Mensajes:
            url:    newsletter_message
  dineromail:
    ipn_url: https://argentina.dineromail.com/Vender/ConsultaPago.asp
    ipn_params:
      Email: ventas@ahorraseguro.com.ar
      Acount: 27906883
      Pin: 44WFM0ESJM
      StartDate: 20120704
      EndDate: 20120802
      XML: 1
