<?php

/**
 * Deal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mendozaoferta
 * @subpackage model
 * @author     diego@cooperativahormigon.com.ar
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class Deal extends BaseDeal
{

  function __toString() {
    return substr($this->getTitle(), 0, 30).'...' ;
  } 

  function increaseBought() {
    $this->setBoughtCount($this->getBoughtCount()+1);
    $this->save();
  } 

  function increaseVisited() {
    $this->setVisitedCount($this->getVisitedCount()+1);
    $this->save();
  } 

  function increasePrinted() {
    $this->setPrintedCount($this->getPrintedCount()+1);
    $this->save();
  } 

  function getValue() {
    return $this->getRealValue() - $this->getDiscount();
  } 

  function getDiscount() {
    return round($this->getRealValue() * ($this->getOffer()/100));
  } 

  function isOpen() {
    return ($this->getTargetTime() - time())>0;
  } 


  function getTargetTime() {
    return $this->getDateTimeObject('ends_at')->getTimestamp();
  } 


  function getThumb($size='s') {
    if ($size == 's'){$w=80;$h=80;}
    elseif($size == 'm'){$w=200;$h=200;}
    elseif($size == 'box'){$w=224;$h=224;}
    elseif($size == 'b'){$w=430;$h=430;}

    $file = sfConfig::get('sf_upload_dir').'/deals/'.$size.'-'.$this->getImage();
    $original = sfConfig::get('sf_upload_dir').'/deals/'.$this->getImage();
    $result = '/uploads/deals/'.$size.'-'.$this->getImage();
    if (($this->getImage()=='') || !file_exists($original)){
      $original = sfConfig::get('sf_web_dir').'/images/no-image.jpg';
      $file = sfConfig::get('sf_upload_dir').'/deals/'.$size.'-no-image.jpg';
      $result = '/uploads/deals/'.$size.'-no-image.jpg';
    }

    if (!file_exists($file)){
      $img = new sfImage($original);
      $img->thumbnail($w,$h,'center');
      $img->setQuality(75);
      $img->saveAs($file);    
    }
    
    return $result;
  } 


  function getAvailable() {

    $available = null;
    if($this->getMaxDeals()){
      //retrieve buys made already
      $conn = Doctrine_Manager::connection();
      $query = $conn->prepare("
        select SUM(p.quantity) AS sum_quantity
        from payment p
        where p.deal_id = :deal_id
      ");
      $query->execute(array('deal_id' => $this->getId() ));
      $result = $query->fetchAll();
      $buyed = $result[0][0];
      $available = $this->getMaxDeals() - $buyed;
    }
    if($this->getMaxPerBuy()){
      if(isset($available)){
        $available = min($available,$this->getMaxPerBuy());
      }else{
        $available = $this->getMaxPerBuy();
      }
    }
    return $available;
    
  } 


}
