<?php

/**
 * NewsletterMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mendozaoferta
 * @subpackage model
 * @author     diego@cooperativahormigon.com.ar
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class NewsletterMessage extends BaseNewsletterMessage
{
  function getProgress() {
    $p = ceil($this->offset_i*100/$this->recipients_count);
    if($p >100){$p =100; }
    
    if($p ==100 && $this->is_active){
      return 99;
    }else{
      return $p;
    }
  } 
  function getElapsedTime() {
    return abs(ceil(($this->recipients_count-$this->offset_i)/$this->limit_i));
  } 
}
