<?php

/**
 * Payment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mendozaoferta
 * @subpackage model
 * @author     diego@cooperativahormigon.com.ar
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class Payment extends BasePayment
{

  public function friendly_status() {
    return PaymentTable::$statuses[$this->getStatus()];
  }

  public function check_status() {
  //checks payment status thru dineromail services

    if ($this->isCompleted()){
      //do not check if it is already completed
      //also a workaround for manual old payments without transaction_id
      return true;
    }

    //todo: put this sensitive data in a secure place
    $url = 'http://argentina.dineromail.com/Vender/Consulta_IPN.asp';
    $tmpl = 'DATA=<REPORTE><NROCTA>%s</NROCTA><DETALLE><CONSULTA><CLAVE>%s</CLAVE><TIPO>1</TIPO><OPERACIONES><ID>%s</ID></OPERACIONES></CONSULTA></DETALLE></REPORTE>';
    $cuenta = '2790688';
    $clave = 'Ipn123Ahorra';
    $data = sprintf($tmpl,$cuenta,$clave,$this->getId());

    $ch = curl_init($url);
     
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
     
    $response = curl_exec($ch);
    curl_close($ch);

    $doc = new SimpleXMLElement($response);


    $values = array();


    if ($doc->ESTADOREPORTE==1){
      $op = $doc->DETALLE->OPERACIONES->OPERACION;

      if ($this->getId() == (int)$op->ID){
        $values = array_merge($values, array(
          'dm_id' => (string)$op->NUMTRANSACCION,
          'dm_bought_on' => date('Y-m-d H:i:s', strtotime($op->FECHA)),
          'dm_amount' => (float)$op->MONTO,
          'dm_net_amount' => (float)$op->MONTONETO,
          'dm_method' => (int)$op->METODOPAGO,
          'dm_medium' => (string)$op->MEDIOPAGO,
          'dm_installments' => (int)$op->CUOTAS,
          'dm_buyer_email' => (string)$op->COMPRADOR->EMAIL,
          'dm_buyer_address' => (string)$op->COMPRADOR->DIRECCION,
          'dm_buyer_comment' => (string)$op->COMPRADOR->COMENTARIO,
          'dm_buyer_name' => (string)$op->COMPRADOR->NOMBRE,
          'dm_buyer_phone' => (string)$op->COMPRADOR->TELEFONO,
          'dm_buyer_tipodoc' => (string)$op->COMPRADOR->TIPODOC,
          'dm_buyer_numdoc' => (string)$op->COMPRADOR->NUMERODOC,
          ));
          
        switch ((int)$op->ESTADO) {
          case 1:
            //PENDIENTE  DE  PAGO
            $values['status'] = 'P';
            break;
          case 2:
            //ACREDITADO
            $values['status'] = 'A';
            $this->getDeal()->increaseBought();
            break;
          case 3:
            //CANCELADO
            $values['status'] = 'C';
            break;
        }
          
      }else{
        $values['status'] = 'E';
      }

    }elseif($doc->ESTADOREPORTE==8){
      $values['status'] = 'E';
    }
    
    $this->fromArray($values);
    $this->save();
    return $this->isCompleted();
  
  } 

  public function isCompleted() {
    return ($this->getStatus()=='A');
  }


}
