# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  fb_fanpage: http://www.facebook.com/AhorraSeguro
  youtube_link: http://www.youtube.com/embed/_xgPtqT0XBY?wmode=transparent 
  from_email: info@ahorraseguro.com.ar
  from_fullname: El Equipo de info@ahorraseguro.com.ar
  contact_phone:  +54 000 000
  contact_email: contacto@ahorraseguro.com.ar
  
  twitter_link: http://twitter.com/AhorraSeguro   
  facebook_link: http://www.facebook.com/AhorraSeguro
  linkedin_link: '#'
  
  sf_guard_plugin:
    routes_register: false  
    signin_form: userSigninForm
    
  dineromail:
    checkout_url: https://checkout.dineromail.com/CheckOut
    email: ventas@ahorraseguro.com.ar
    checkout_params:
      tool: button
      merchant: 2790688
      country_id: 1
      seller_name: ventas@ahorraseguro.com.ar
      languge: es
      currency: ars
      header_image: http://ahorraseguro.com.ar/images/dineromail_logo.png
      change_quantity: 0
      expanded_sale_detail: 1
      payment_method_available: all      
