homepage:
  url:   /
  param: { module: deals, action: index }

big_deals:
  url:   /
  param: { module: deals, action: index }

deals:
  url:   /ofertas
  param: { module: deals, action: deals }

yapa_deals:
  url:   /yapas
  param: { module: deals, action: deals, yapa: true }

deals_by_category:
  url:   /ofertas/de/:category_id/:yapa
  param: { module: deals, action: deals, yapa: false }

deals_by_category_and_quarter:
  url:   /ofertas/de/:category_id/en/:quarter_id/:yapa
  param: { module: deals, action: deals, yapa: false  }



closed_deals:
  url:   /recientes
  param: { module: deals, action: closed }

deal:
  url:   /oferta/:id
  class:    sfDoctrineRoute
  param: { module: deals, action: show }
  options:  { model: Deal, type: object }



buy:
  url:   /buy/:id
  class:    sfDoctrineRoute
  param: { module: deals, action: checkout }
  options:  { model: Deal, type: object }

pay:
  url:   /pay
  param: { module: deals, action: pay }

payment_ok:
  url:   /payment_ok/:id
  class:    sfDoctrineRoute
  param: { module: deals, action: paymentOk }
  options:  { model: Payment, type: object }

payment_error:
  url:   /payment_error/:id
  class:    sfDoctrineRoute
  param: { module: deals, action: paymentError }
  options:  { model: Payment, type: object }



payment_pending:
  url:   /payment_pending/:id
  class:    sfDoctrineRoute
  param: { module: deals, action: paymentPending }
  options:  { model: Payment, type: object }



#contact
contact_us:
  url:   /contactanos
  param: { module: contact_us, action: index }

contact_us_sent:
  url:  /contactanos/enviado
  param: { module: contact_us, action: sent }


#static
about_us:
  url:   /quienes-somos
  param: { module: static, action: aboutUs }
faq:
  url:   /faq
  param: { module: static, action: faq }
how_it_works:
  url:   /como-funciona
  param: { module: static, action: howItWorks }
privacy_policy:
  url:   /legales
  param: { module: static, action: privacyPolicy }


#user
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
user_signup:
  url:   /register
  param: { module: users, action: register }
user_suscribe:
  url:   /suscribe
  param: { module: users, action: suscribe }
user_unsuscribe:
  url:   /unsuscribe/:token
  param: { module: users, action: unsuscribe }
user_deals:
  url:   /user_deals
  param: { module: users, action: deals }
user_boucher:
  url:   /boucher/:id
  class:    sfDoctrineRoute
  param: { module: users, action: boucher }
  options:  { model: Payment, type: object }
user_savings:
  url:   /user_savings
  param: { module: users, action: savings }
user_account:
  url:   /user_account
  param: { module: users, action: account }
user_edit_account:
  url:   /user_edit_account
  param: { module: users, action: editAccount }
user_change_password:
  url:   /user_change_password
  param: { module: users, action: changePassword }
  
#mails
mail_test:
  url:   /mail_test
  param: { module: mails, action: index }

