default:
  http_metas:
    content-type: text/html
  metas:
    title:        Ahorra Seguro
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
  stylesheets:    [main.css , print.css: { media: print } , ie6.css: { condition: IE 6 }]
  javascripts:    [jquery-1.5.1.min.js, site.js]
  has_layout:     true
  layout:         layout
