generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Store
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          store
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing   #setting the css to a placeholder 

    config:
      actions: ~
      fields:
        name: { label: "Razón Social" }
        trading_name: { label: "Nombre de Fantasía" }
        address: { label: "Domicilio Comercial" }
        city: { label: "Localidad" }
        province: { label: "Provincia" }
        phone: { label: "Teléfono" }
        quarter: { label: "Barrio (obsoleto)", params: disabled=false, help: "Solo de referencia. Este campo se eliminará. Utilice el siguiente para indicar barrio." }
        quarter_id: { label: "Barrio" }
        email: { label: "Correo Electrónico" }
        web: { label: "Sitio Web" }
        salesman_and_position: { label: "Representante/cargo" }
        cuit: { label: "CUIT" }
        condicion_iva: { label: "Condicion frente al IVA" }
        bank: { label: "Banco" }
        bank_account: { label: "Nro de Cuenta" }
        bank_cbu: { label: "CBU" }
      list:
        title: Listado de Comercios
        display: [name, trading_name, cuit, condicion_iva]
      filter: 
        display: [name, trading_name, cuit, condicion_iva]

      form:    ~
      edit:
        title: Editar Comercio
      
      new:
        title: Nuevo Comercio
      
