generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing   #setting the css to a placeholder 

    config:
      actions: ~
      fields:
        name: { label: "Nombre" }
      list:
        title: Listado de Categorías
        display: [name]
      filter: 
        display: [name]

      form:    ~
      edit:
        title: Editar Categoría
      
      new:
        title: Nueva Categoría
      
