<?php slot('body_class','single_column') ?>
<div class="content">
  <h1>AHORRA SEGURO - TÉRMINOS Y CONDICIONES</h1>
  <p>
    I. INTRODUCCIÓN:
  </p>
  <p>
    EL PRESENTE SITIO WEB UBICADO EN LA DIRECCIÓN WWW.AHORRASEGURO.COM.AR, LOS SERVICIOS PRESTADOS POR
    SU INTERMEDIO, Y CUALQUIERA DE LAS PÁGINAS QUE SE PUEDA ACCEDER A TRAVÉS DEL MISMO, EL ADELANTE
    EL “SITIO”, Y QUE ES PROVISTO POR AHORRA SEGURO, EN ADELANTE “ADMINISTRACIÓN DIGITAL S.R.L..”; Y SU ACCESO,
    SE ENCUENTRA CONDICIONADO A LA ACEPTACIÓN COMPLETA DEL PRESENTE ACUERDO QUE CONTIENE LAS
    CONDICIONES Y TÉRMINOS DEL SERVICIO, EN ADELANTE LOS “TÉRMINOS DEL SERVICIO”. EL ACCESO AL SITIO, EN FORMA
    DIRECTA O INDIRECTA, Y SU USO Y/O DESCARGA DE INFORMACIÓN CONTENIDA EN ÉL SUPONE QUE UD. ACEPTA LOS
    PRESENTES TÉRMINOS DEL SERVICIO EN TODAS SUS PARTES. POR EL CONTRARIO SI UD. NO ACEPTARE LOS PRESENTES
    TÉRMINOS DEL SERVICIO, DEBERÁ ABSTENERSE DE ACCEDER A ESTE SITIO, YA SEA DIRECTA O INDIRECTAMENTE, Y DE
    UTILIZAR CUALQUIER INFORMACIÓN O SERVICIO PROVISTA POR EL MISMO.
  </p>
  <p>
    PARA LOS EFECTOS DEL PRESENTE ACUERDO, LA ABREVIACIÓN “UD.” Y LAS PALABRAS “USTED” O “USUARIO”
    REPRESENTAN A CUALQUIER PERSONA NATURAL O JURÍDICA, AGRUPACIÓN SIN PERSONALIDAD LEGAL, O
    REPRESENTANTE EN CUALQUIER FORMA DE LOS MISMOS, QUE USE LOS SERVICIOS Y/O INFORMACIÓN CONTENIDAS EN
    EL SOFTWARE O EL SITIO WEB.
    PRIVACIDAD Y CONFIDENCIALIDAD:
    EL USUARIO DECLARA CONOCER Y ACEPTAR LA POLÍTICA DE CONFIDENCIALIDAD Y SE OBLIGA A GUARDAR ABSOLUTA
    RESERVA SOBRE LOS DATOS AQUÍ PROPORCIONADOS.
  </p>
  <p>
    TODA LA INFORMACIÓN PERSONAL PROPORCIONADA POR UD., INCLUIDOS LOS DATOS PARA LOS DESPACHOS ES DE
    RESPONSABILIDAD EXCLUSIVA DE QUIÉN LA APORTA, Y SOLO SERÁ UTILIZADA POR AHORRASEGURO ADMINISTRACIÓN
    DIGITAL S.R.L. PARA REGISTRARLO EN LOS PROGRAMAS Y SERVICIOS, CREAR CUENTAS PERSONALES, PROCESAR Y
    DARLE SEGUIMIENTO A LOS PEDIDOS, CONTESTAR CORREOS ELECTRÓNICOS Y PROPORCIONARLE INFORMACIÓN CON
    RESPECTO A SU CUENTA Y RESPECTO DE LOS BIENES Y SERVICIOS CONTRATADOS.
  </p>
  <p>
    AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L.. SE RESERVA EL DERECHO DE USAR ESTA INFORMACIÓN PARA ENVIAR
    CORREOS ELECTRÓNICOS CON INFORMACIÓN RELATIVA A SU CUENTA O DE LOS BIENES Y SERVICIOS CONTRATADOS,
    COMO TAMBIÉN PARA ENVIAR INFORMACIÓN SOBRE PROMOCIONES, PRODUCTOS O SERVICIOS QUE LE PUEDAN
    INTERESAR, A MENOS QUE USTED INDIQUE QUE NO DESEA RECIBIR DICHOS CORREOS ELECTRÓNICOS.
  </p>
  <p>
    AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. NO VENDERÁ, ARRENDARÁ O INTERCAMBIARÁ CON TERCEROS LA
    INFORMACIÓN PERSONAL QUE USTED NOS PROPORCIONE.
    PROPIEDAD INTELECTUAL E INDUSTRIAL:
    EL CONTENIDO, ORGANIZACIÓN, GRÁFICAS, DISEÑO, COMPILACIÓN Y OTROS ASPECTOS DEL SITIO SE ENCUENTRAN
    PROTEGIDOS POR LEYES DE PROPIEDAD INTELECTUAL. LA COPIA, REDISTRIBUCIÓN, USO O PUBLICACIÓN POR UD. DE
    CUALQUIERA DE TALES MATERIAS O PARTES ESTA PROHIBIDA POR LA LEY.
  </p>
  <p>
    LA PUBLICACIÓN O TRANSMISIÓN DE LA INFORMACIÓN O DE DOCUMENTOS EN ESTE SITIO, NO CONSTITUYE UNA
    RENUNCIA DE CUALQUIER DERECHO RELACIONADO CON TALES DOCUMENTOS O INFORMACIONES.
  </p>
  <p>
    EL ACCESO, IMPRESIÓN, DESCARGA O TRANSMISIÓN DE CUALQUIER CONTENIDO, GRÁFICAS, IMÁGENES, LOGOTIPOS,
    FORMULARIOS O DOCUMENTOS DEL SITIO, LE OTORGA AL USUARIO ÚNICAMENTE EL DERECHO LIMITADO Y NO
    EXCLUSIVO PARA SU USO PROPIO, Y NO PARA SU REPUBLICACIÓN DISTRIBUCIÓN, CESIÓN, SUBLICENCIA, VENTA O
    CUALQUIER OTRO USO.
  </p>
  <p>
    EN CASO DE QUE LOS USUARIOS DESEEN UTILIZAR LAS MARCAS, NOMBRES, LOGOS O CUALQUIER OTRO SIGNO
    DISTINTIVO DISPONIBLE EN EL SITIO, Y QUE SEAN DE PROPIEDAD DE AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. ,
    PUEDE SOLICITAR LA AUTORIZACIÓN NECESARIA PONIÉNDOSE EN CONTACTO CON AHORRASEGURO ADMINISTRACIÓN
    DIGITAL S.R.L. DIRIGIÉNDOSE AL MISMO POR LOS MEDIOS DE CONTACTO INDICADOS EN LOS PRESENTES TÉRMINOS DEL
    SERVICIO.
  </p>
  <p>
    AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. HACE EXPRESA RESERVA DEL EJERCICIO DE TODAS LAS ACCIONES
    TANTO CIVILES COMO PENALES DESTINADAS AL RESGUARDO DE SUS LEGÍTIMOS DERECHOS DE PROPIEDAD
    INTELECTUAL E INDUSTRIAL.
    ACCESO AL SITIO:
    EL ACCESO AL SITIO ESTÁ RESTRINGIDO A LOS USUARIOS AUTORIZADOS, PREVIA SUSCRIPCIÓN DE LOS MISMOS AL
    SERVICIO. PARA EL ACCESO A DETERMINADOS SERVICIOS SE REQUIERE EL REGISTRO DE USUARIO EN LAS BASES DE
    DATOS DE AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L.
  </p>
  <p>
    ES OBLIGACIÓN DEL USUARIO EL CUSTODIAR SUS DATOS Y CLAVES DE ACCESO, PUESTO QUE SON PARA EL
    USO EXCLUSIVO DEL TITULAR DE LAS MISMAS, Y SU CUSTODIA Y CORRECTA UTILIZACIÓN SON DE SU ENTERA
    RESPONSABILIDAD, RESPONDIENDO POR TANTO DE LAS VIOLACIONES A LAS OBLIGACIONES DE CONFIDENCIALIDAD Y
    PRIVACIDAD DE LA INFORMACIÓN CONTENIDA EN EL SITIO.
  </p>
  <p>
    OBLIGACIONES SOBRE LA VERACIDAD DE LA INFORMACIÓN:
  </p>
  <p>
    TODA LA INFORMACIÓN QUE PROPORCIONE EL USUARIO A AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. DEBERÁ
    SER VERAZ Y COMPROBABLE. PARA ESTOS EFECTOS EL USUARIO GARANTIZA LA AUTENTICIDAD DE TODOS LOS
    DATOS PROPORCIONADOS, Y LA ACTUALIZACIÓN DE LOS MISMOS, SIENDO ÉSTE RESPONSABLE POR LOS DAÑOS
    QUE CUALQUIER INEXACTITUD PUEDA CAUSARLE AL MISMO, A AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. O A
  </p>
  <p>
    TERCEROS.
  </p>
  <p>
    VÍNCULOS:
    EL PRESENTE SITIO PUEDE CONTENER HIPERVÍNCULOS A OTROS SITIOS WEB, QUE NO SEAN CONTROLADOS, EDITADOS,
    NI TENGAN RELACIÓN LEGAL ALGUNA CON LOS SITIOS DE AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. , NO SIENDO
    ESTA RESPONSABLE POR TANTO DEL CONTENIDO NI LA EXACTITUD DE LA INFORMACIÓN CONTENIDA EN ELLOS.
  </p>
  <p>
    LA FUNCIÓN DE LOS LINKS QUE SE ENCUENTRAN EN ESTE SITIO ES MERAMENTE INFORMATIVA, Y SE LIMITA SOLO
    A DAR A CONOCER AL USUARIO OTRAS FUENTES DE INFORMACIÓN RELACIONADAS A LAS MATERIAS PROPIAS DEL
    SITIO. AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. EN NINGÚN CASO ES RESPONSABLE DE LA INFORMACIÓN
    QUE DIRECTA O INDIRECTAMENTE SE PUEDA OBTENER DE LOS SITIOS A LOS QUE SE ACCEDA A TRAVÉS DE LOS
    HIPERVÍNCULOS CONTENIDOS EN EL SITIO.
  </p>
  <p>
    AQUELLOS USUARIOS QUE DESEEN ESTABLECER HIPERVÍNCULOS CON EL SITIO DEBERÁN ABSTENERSE DE REALIZAR
    MANIFESTACIONES FALSAS, INEXACTAS O INCORRECTAS SOBRE EL SITIO O SU CONTENIDO.
  </p>
  <p>
    EN NINGÚN CASO SE DARÁ A ENTENDER QUE AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. AUTORIZA EL
    HIPERVÍNCULO, O QUE SUPERVISA, APRUEBA O ASUME DE CUALQUIER FORMA LOS CONTENIDOS O SERVICIOS
    OFRECIDOS O PUESTOS A DISPOSICIÓN EN LA PÁGINA WEB EN LA QUE SE ESTABLEZCA EL VÍNCULO AL SITIO.
  </p>
  <p>
    EL ESTABLECIMIENTO DE ESTOS VÍNCULOS NO IMPLICA EN FORMA ALGUNA LA EXISTENCIA DE RELACIÓN ALGUNA ENTRE
    AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. Y EL TITULAR DE LA PAGINA WEB EN LA QUE SE ESTABLEZCA EL
    MISMO.
  </p>
  <p>
    CAPACIDAD:
    LOS SERVICIOS SÓLO ESTÁN DISPONIBLES PARA PERSONAS QUE TENGAN CAPACIDAD LEGAL PARA CONTRATAR.
    NO PODRÁN UTILIZAR LOS SERVICIOS LAS PERSONAS QUE NO TENGAN ESA CAPACIDAD, LOS MENORES DE EDAD O
    USUARIOS QUE HAYAN SIDO SUSPENDIDOS TEMPORALMENTE O INHABILITADOS DEFINITIVAMENTE.
  </p>
  <p>
    CAMBIO DE LOS TÉRMINOS DE SERVICIO:
  </p>
  <p>
    NOS RESERVAMOS EL DERECHO, EN CUALQUIER TIEMPO, DE MODIFICAR, ADICIONAR, ELIMINAR, ALTERAR Y PONER AL
    DÍA LOS PRESENTES TÉRMINOS DEL SERVICIO. LOS CAMBIOS REFERIDOS SE HARÁN EFECTIVOS INMEDIATAMENTE UNA
    VEZ NOTIFICADOS LOS MISMOS, LA CUAL PODRÁ EFECTUARSE POR CUALQUIER MEDIO FEHACIENTE, ENTRE OTRAS,
    POR SU PUBLICACIÓN EN EL SITIO. SERÁ DE SU RESPONSABILIDAD REVISAR PERIÓDICAMENTE LOS TÉRMINOS DE
    SERVICIO EN EL SITIO. SU USO DEL PRESENTE SITIO CON POSTERIORIDAD A HABERSE EFECTUADO ALGÚN CAMBIO EN
    LOS TÉRMINOS DE SERVICIO, CONSTITUIRÁ UNA ACEPTACIÓN EXPRESA DE LOS MISMOS.
  </p>
  <p>
    PROHIBICIONES:
    ADEMÁS DE LAS PROHIBICIONES QUE EXPRESAMENTE SE CONTENGAN EN OTRAS SECCIONES DE LOS PRESENTES
    TÉRMINOS DEL SERVICIO, SE PROHÍBE A LOS USUARIOS USAR EL SITIO DE CUALQUIER FORMA QUE PUDIERE
    DAÑAR, DESHABILITAR, AFECTAR O SOBRECARGAR EL SITIO; CARGAR, HACER AVISOS O DE CUALQUIER OTRA
    FORMA TRANSMITIR O DISTRIBUIR EN ESTE SITIO CUALQUIER ÍTEM, INCLUYENDO SIN LIMITACIÓN ALGUNA VIRUS
    COMPUTACIONALES, CABALLOS TROYANOS, GUSANOS, MECANISMOS DE APAGADO AUTOMÁTICO O CUALQUIER OTRO
    SISTEMA, PROGRAMA O ARCHIVO DISRUPTIVO; INTERFERIR CON LA SEGURIDAD DE ESTE SITIO; INFRINGIR PATENTES
    COMERCIALES, MARCAS REGISTRADAS, SECRETOS COMERCIALES E INDUSTRIALES, DERECHOS DE PUBLICIDAD O
    CUALQUIER OTROS DERECHOS PROPIETARIOS DE CUALQUIER PERSONA NATURAL O JURÍDICA, COLECTIVIDADES, ETC.;
    IMPEDIR O INTERRUMPIR EL USO DEL SITIO POR PARTE DE TERCEROS; USAR PROGRAMAS AUTOMÁTICOS, MECANISMOS
    O PROCESOS MANUALES PARA MONITOREAR, COPIAR, RESUMIR, O EXTRAER INFORMACIÓN DE CUALQUIER OTRA FORMA
    DESDE ESTE SITIO; USAR LAS CUENTAS Y CLAVES DE TERCEROS USUARIOS, O CUALQUIER OTRA INFORMACIÓN SIN EL
    CONSENTIMIENTO PREVIO Y POR ESCRITO DE SU TITULAR; CREAR CUENTAS O UTILIZAR EL SITIO PROPORCIONANDO
    DATOS FALSOS; TRANSMITIR DESDE ESTE SITIO SPAM, CADENAS, CORREO BASURA O CUALQUIER OTRO TIPO DE
    CORREO MASIVO NO SOLICITADO; CARGAR, DISTRIBUIR O DISEMINAR DESDE EL SITIO MATERIAL O INFORMACIÓN
    AMENAZANTE, DE ACOSO, DIFAMATORIO, OBSCENO, PORNOGRÁFICO, FRAUDULENTO, ENGAÑADOR, O QUE DE
    CUALQUIER OTRA FORMA PUDIERE SER ATENTATORIO CONTRA LA LEY, LAS BUENAS COSTUMBRES O QUE VIOLE LOS
    DERECHOS DE CUALQUIER OTRA PARTE, O QUE CONTENGA SOLICITUDES DE RECAUDACIÓN DE FONDOS, ENTRE OTRAS.
  </p>
  <p>
    FALLAS DE SISTEMA:
    AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. NO SE RESPONSABILIZA POR CUALQUIER DAÑO, PERJUICIO O
    PÉRDIDA AL USUARIO CAUSADOS POR FALLAS EN EL SOFTWARE, EN EL SERVIDOR O EN INTERNET. AHORRASEGURO
    ADMINISTRACIÓN DIGITAL S.R.L. TAMPOCO SERÁ RESPONSABLE POR CUALQUIER VIRUS QUE PUDIERA INFECTAR
    EL EQUIPO DEL USUARIO COMO CONSECUENCIA DEL ACCESO, USO O EXAMEN DEL SITIO O A RAÍZ DE CUALQUIER
    TRANSFERENCIA DE DATOS, ARCHIVOS, IMÁGENES, TEXTOS, O AUDIO CONTENIDOS EN EL MISMO.
  </p>
  <p>
    LOS USUARIOS NO PODRÁN IMPUTARLE RESPONSABILIDAD ALGUNA NI EXIGIR PAGO POR LUCRO CESANTE, EN VIRTUD
    DE PERJUICIOS RESULTANTES DE DIFICULTADES TÉCNICAS O FALLAS EN EL SOFTWARE, LOS SISTEMAS O EN INTERNET.
    AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. NO GARANTIZA EL ACCESO Y USO CONTINUADO O ININTERRUMPIDO
    DE SU SITIO. EL SISTEMA PUEDE EVENTUALMENTE NO ESTAR DISPONIBLE DEBIDO A DIFICULTADES TÉCNICAS O
    FALLAS DE INTERNET, O POR CUALQUIER OTRA CIRCUNSTANCIA AJENA A AHORRASEGURO ADMINISTRACIÓN DIGITAL
    S.R.L. ; EN TALES CASOS SE PROCURARÁ RESTABLECERLO CON LA MAYOR CELERIDAD POSIBLE SIN QUE POR ELLO
    PUEDA IMPUTÁRSELE ALGÚN TIPO DE RESPONSABILIDAD. AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. NO SERÁ
  </p>
  <p>
    RESPONSABLE POR NINGÚN ERROR U OMISIÓN CONTENIDOS EN EL SITIO WEB.
  </p>
  <p>
    RESPONSABILIDAD:
    AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. NO ES RESPONSABLE POR LA PÉRDIDA O EL DAÑO EVENTUAL
    QUE PUEDAN SUFRIR LOS ARCHIVOS QUE LE SON ENVIADOS PARA LA PRESTACIÓN DE SUS SERVICIOS, YA SEA POR
    PROBLEMAS TÉCNICOS, HECHO SUYOS O DE SUS DEPENDIENTES, RAZÓN POR LA QUE ES RESPONSABILIDAD DEL
    USUARIO EL RESPALDO DE LA INFORMACIÓN QUE SE ENVÍA PARA LA PRESTACIÓN DE LOS SERVICIOS.
  </p>
  <p>
    JURISDICCIÓN Y LEY APLICABLE:
    ESTE ACUERDO ESTARÁ REGIDO POR LAS LEYES DE LA REPÚBLICA ARGENTINA.
  </p>
  <p>
    CUALQUIER CONTROVERSIA DERIVADA DEL PRESENTE ACUERDO, SU EXISTENCIA, VALIDEZ, INTERPRETACIÓN, ALCANCE
    O CUMPLIMIENTO, SERÁ SOMETIDA A LAS LEYES APLICABLES Y A LOS TRIBUNALES COMPETENTES DE LA CIUDAD DE
    BUENOS AIRES , Y LOS PROCEDIMIENTOS SE LLEVARÁN A CABO EN IDIOMA CASTELLANO.
  </p>
  <p>
    II. CONDICIONES DE VENTA
    AL PONER UNA ORDEN DE COMPRA, USTED NOS OTORGA UN MANDATO PARA HACER UNA OFERTA PARA ADQUIRIR
    EL O LOS CUPONES DE DESCUENTO QUE HA SELECCIONADO EN LOS TÉRMINOS Y CONDICIONES ESTABLECIDOS A
    CONTINUACIÓN.
  </p>
  <p>
    USTED ESTÁ OBLIGADO A CREAR UNA CUENTA PARA LA COMPRA DE CUALQUIER PRODUCTO O SERVICIO. ESTA
    INFORMACIÓN ES NECESARIA PARA QUE PODAMOS OFRECER UN ACCESO FÁCIL AL SISTEMA, Y PARA IMPRIMIR SUS
    PEDIDOS, VER SUS COMPRAS ANTERIORES, MODIFICAR SUS PREFERENCIAS, Y PARA ASEGURAR EL USO AUTORIZADO DE
    LOS CUPONES ADQUIRIDOS.
  </p>
  <p>
    EL CUPÓN QUE USTED COMPRA A TRAVÉS DE AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. SE PUEDE
    CANJEAR POR PRODUCTOS O SERVICIOS POR PARTE DEL VENDEDOR DE BIENES Y SERVICIOS, DENOMINADO EN LO
    SUCESIVO "COMERCIANTE". EL COMERCIANTE, NO AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. , ES EL VENDEDOR
    DE LOS BIENES Y SERVICIOS Y ES EL ÚNICO RESPONSABLE DE ENTREGAR EL PRODUCTO O PRESTAR EL SERVICIO DE
    CUALQUIER CUPÓN QUE USTED COMPRA A TRAVÉS DEL SISTEMA AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L..
  </p>
  <p>
    TÉRMINOS Y CONDICIONES ADICIONALES PARA TODOS LOS PRODUCTOS Y SERVICIOS OFRECIDOS A TRAVÉS DE
    AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L.
    TODOS LOS CUPONES IMPRESOS, DESCARGADOS, O DE CUALQUIER FORMA RECIBIDOS DESDE EL SITIO O DE CUALQUIER
    SITIO WEB ASOCIADO CON LOS CUPONES DE AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L.. (EN LO SUCESIVO,
    LOS "CUPONES") SON VALES DE PROMOCIÓN QUE SE OFRECEN A LOS CLIENTES POR DEBAJO DEL VALOR NOMINAL
    HABITUAL DE LOS BIENES O SERVICIOS, Y ESTARÁ SUJETO A LOS TÉRMINOS Y CONDICIONES DE AHORRASEGURO
    ADMINISTRACIÓN DIGITAL S.R.L. Y DEL COMERCIANTE. EL COMERCIANTE ES EL VENDEDOR DE LOS BIENES O SERVICIOS
    QUE USTED ESTÁ COMPRANDO.
  </p>
  <p>
    EL TITULAR Y EL EMISOR DE LOS CUPONES ES EL COMERCIANTE. COMO TITULAR Y EMISOR DEL CUPÓN, EL
    COMERCIANTE SERÁ PLENAMENTE RESPONSABLE DE CUALQUIER Y TODAS LAS LESIONES, ENFERMEDADES, DAÑOS Y
    PERJUICIOS, DEMANDAS, RESPONSABILIDADES Y COSTOS SUFRIDOS POR O EN RELACIÓN CON UN CLIENTE, CAUSADOS
    EN SU TOTALIDAD O EN PARTE POR EL COMERCIANTE, ASÍ COMO DE CUALQUIER RESPONSABILIDAD DERIVADA DE
    CUPONES NO CANJEADOS. LOS DESCUENTOS INCORPORADOS EN LOS CUPONES NO PUEDEN SER REEMBOLSADOS
    TOTAL O PARCIALMENTE NI PUEDEN SER ACUMULADOS CON OTRAS PROMOCIONES QUE TENGA VIGENTES EL
    COMERCIANTE AL MOMENTO DE SU CANJE.
  </p>
  <p>
    LOS CUPONES SIEMPRE SE ENTENDERÁN VENDIDOS BAJO LAS SIGUIENTES CONDICIONES:
  </p>
  <p>
    EL CUPÓN SOLO SERÁ APLICABLE AL VALOR DE LAS MERCANCÍAS VENDIDAS POR EL COMERCIANTE Y NUNCA SERÁ
    APLICABLE A COSTOS DE ENVÍO DE LAS MISMAS, MIENTRAS NO SE ESPECIFIQUE LO CONTRARIO EN LA PUBLICACIÓN DEL
    MISMO.
  </p>
  <p>
    NI AHORRASEGURO ADMINISTRACIÓN DIGITAL S.R.L. NI EL COMERCIANTE SON RESPONSABLES DE LA PÉRDIDA O ROBO
    DEL CUPÓN O CUPONES O DE EL O LOS NÚMEROS DE REFERENCIA DE ESTOS.
  </p>
  <p>
    LA REPRODUCCIÓN, LA VENTA O EL COMERCIO DE LOS CUPONES ESTÁ TOTALMENTE PROHIBIDA SALVO QUE SE REALICE
    EN CONFORMIDAD CON LA LEY.
  </p>
  <p>
    UNA VEZ CONCRETADA LA OFERTA DE LOS CUPONES DE DESCUENTO POR PARTE DE AHORRASEGURO ADMINISTRACIÓN
    DIGITAL S.R.L. , LOS CLIENTES PIERDEN CUALQUIER DERECHO DE RETRACTO SOBRE EL MANDATO DE COMPRA POR LOS
    CUPONES DE DESCUENTO.
  </p>
  <p>
    LA OFERTA DE LOS CUPONES, INCLUYENDO PERO NO LIMITADO A LOS DESCUENTOS, EXPIRARÁ EN LA FECHA
    ESPECIFICADA EN RESPECTIVO CUPÓN, QUEDANDO LIBRE EL COMERCIANTE DE CUMPLIR CON LAS OBLIGACIONES
    INDICADAS EN EL CUPÓN UNA VEZ VENCIDO ESTE PLAZO.  
  </p>
</div>
