generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Payment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          payment
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing   #setting the css to a placeholder 

    config:
      actions: ~
      fields:
        created_at: { label: "Fecha" }
        status: { label: "Estado" }
        deal: { label: "Oferta" }
        user: { label: "Usuario" }
        price: { label: "Precio" }
        offer: { label: "Porcentaje" }
        real_value: { label: "Valor Real" }
        saved: { label: "Dinero Ahorrado" }
        code: { label: "Código" }

      list:
        title: Listado de Pagos
        #layout: stacked
        display: [id, status,created_at,code, price, deal, user]
        object_actions:
          complete: {label: Comprobar, action: check}
          
      filter:
        display: [status, deal_id, user_id, created_at]
