generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NewsletterMessage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          newsletter_message
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing   #setting the css to a placeholder 

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Mensajes
        display:
          - created_at
          - is_active
        
        object_actions:
          preview: {label: Previsualizar, action: preview}
          status: {label: Estado, action: status}
      filter:
        display: [is_active]
      form:    ~
      edit:    ~
      new:     ~
