generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Deal
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          deal
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing   #setting the css to a placeholder 

    config:
      actions: ~

      fields:
        is_oferton: { label: "Es un Ofertón?" }
        has_yapa: { label: "Tiene Yapa?" }
        category_id: { label: "Categoría" }
        store_id: { label: "Comercio" }
        seller_id: { label: "Vendedor" }
        title: { label: "Titulo" }
        newsletter_title: { label: "Titulo para Newsletter" }
        description: { label: "Descripción" }
        featured: { label: "Destacado" }
        conditions: { label: "Condiciones" }
        starts_at: { label: "Empieza" }
        ends_at: { label: "Termina" }
        image: { label: "Imagen" }
        offer: { label: "Porcentaje" }
        real_value: { label: "Valor Real" }
        bought_count: { label: "Cantidad comprada" }
        visited_count: { label: "Cantidad de visitas" }
        printed_count: { label: "Cantidad impresa" }
        max_per_buy: { label: "Cantidad máxima por compra", help: "Dejar en blanco si no hay límite" }
        max_deals: { label: "Cantidad máxima de ofertas", help: "Dejar en blanco si no hay límite"  }

        
      list:
        title: Listado de Ofertas
        layout: stacked
        display: [title]
        params: |
          %%_thumb%%
          %%_stats%%
          <h4>%%=title%%</h4>
          <em>%%=category%%</em>
        object_actions:
          _edit: ~
          _delete: ~
          payments: {label: Operaciones, action: payments}
      filter:
        display: [active, category_id, title]
      form:
        display:
          General: [ is_oferton, has_yapa, category_id, store_id, quarter_id, seller_id, title, newsletter_title]
          Contenido: [description, featured, conditions]
          Fechas: [starts_at, ends_at]
          Media: [image]
          Precios: [_offer, real_value]
          Parámetros: [max_per_buy, max_deals, bought_count, visited_count, printed_count]
      edit:
        title: Editar Oferta
      
      new:
        title: Nueva Oferta

