<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_guard_user_profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => '80',
             ),
             'fullname' => 
             array(
              'type' => 'string',
              'length' => '80',
             ),
             'validate' => 
             array(
              'type' => 'string',
              'length' => '17',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('deal', 'bought_count', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('sf_guard_user_profile');
        $this->removeColumn('deal', 'bought_count');
    }
}