<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('sf_guard_user_profile');
        $this->createTable('newsletter_email', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => '80',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->createTable('sf_guard_user_profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => '80',
             ),
             'fullname' => 
             array(
              'type' => 'string',
              'length' => '80',
             ),
             'validate' => 
             array(
              'type' => 'string',
              'length' => '17',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->dropTable('newsletter_email');
    }
}