<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('deal', 'excerpt');
        $this->addColumn('deal', 'visited_count', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('deal', 'printed_count', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('deal', 'featured', 'string', '4000', array(
             'notnull' => '1',
             ));
        $this->addColumn('deal', 'conditions', 'string', '4000', array(
             'notnull' => '1',
             ));
        $this->addColumn('deal', 'seller', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('deal', 'category_id', 'integer', '8', array(
             ));
        $this->changeColumn('deal', 'title', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('deal', 'excerpt', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->removeColumn('deal', 'visited_count');
        $this->removeColumn('deal', 'printed_count');
        $this->removeColumn('deal', 'featured');
        $this->removeColumn('deal', 'conditions');
        $this->removeColumn('deal', 'seller');
    }
}