<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('payment', 'sf_guard_user_id');
        $this->addColumn('payment', 'user_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('payment', 'sf_guard_user_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->removeColumn('payment', 'user_id');
    }
}