<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('payment', 'payment_deal_id_deal_id', array(
             'name' => 'payment_deal_id_deal_id',
             'local' => 'deal_id',
             'foreign' => 'id',
             'foreignTable' => 'deal',
             ));
        $this->addIndex('payment', 'payment_deal_id', array(
             'fields' => 
             array(
              0 => 'deal_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('payment', 'payment_deal_id_deal_id');
        $this->removeIndex('payment', 'payment_deal_id', array(
             'fields' => 
             array(
              0 => 'deal_id',
             ),
             ));
    }
}