<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('payment', 'quantity', 'integer', '8', array(
             'notnull' => '1',
             ));
    }
    
    public function postUp()
    {
         Doctrine_Manager::getInstance()
          ->getCurrentConnection()
          ->execute('UPDATE payment p SET p.quantity = 1');
    }
    
    public function down()
    {
        $this->removeColumn('payment', 'quantity');
    }
}
