<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('payment', 'code', 'integer', '8', array(
             ));
    }
    public function postUp()
    {
         Doctrine_Manager::getInstance()
          ->getCurrentConnection()
          ->execute('UPDATE payment p SET p.code = 1000 + p.id');
    }
    
    public function down()
    {
        $this->removeColumn('payment', 'code');
    }
}
