<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('payment', 'offer', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('payment', 'real_value', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function postUp()
    {
         Doctrine_Manager::getInstance()
          ->getCurrentConnection()
          ->execute('UPDATE payment p inner join deal d on p.deal_id=d.id SET p.offer = d.offer, p.real_value= d.real_value');
    }
    
    public function down()
    {
        $this->removeColumn('payment', 'offer');
        $this->removeColumn('payment', 'real_value');
    }
}
