<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('newsletter_message', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'from_email' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'from_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'subject' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'body' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '4000',
             ),
             'last_recipient_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'recipients_count' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'sent_count' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('newsletter_email', 'is_active', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->dropTable('newsletter_message');
        $this->removeColumn('newsletter_email', 'is_active');
    }
}