<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('newsletter_message', 'last_recipient_id');
        $this->addColumn('newsletter_message', 'limit_i', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('newsletter_message', 'offset_i', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('newsletter_message', 'last_recipient_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->removeColumn('newsletter_message', 'limit_i');
        $this->removeColumn('newsletter_message', 'offset_i');
    }
}
