<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('deal', 'seller_id', 'integer', '8', array(
             ));
        $this->addColumn('deal', 'store_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('deal', 'seller_id');
        $this->removeColumn('deal', 'store_id');
    }
}