<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('deal', 'deal_seller_id_seller_id', array(
             'name' => 'deal_seller_id_seller_id',
             'local' => 'seller_id',
             'foreign' => 'id',
             'foreignTable' => 'seller',
             ));
        $this->createForeignKey('deal', 'deal_store_id_store_id', array(
             'name' => 'deal_store_id_store_id',
             'local' => 'store_id',
             'foreign' => 'id',
             'foreignTable' => 'store',
             ));
        $this->addIndex('deal', 'deal_seller_id', array(
             'fields' => 
             array(
              0 => 'seller_id',
             ),
             ));
        $this->addIndex('deal', 'deal_store_id', array(
             'fields' => 
             array(
              0 => 'store_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('deal', 'deal_seller_id_seller_id');
        $this->dropForeignKey('deal', 'deal_store_id_store_id');
        $this->removeIndex('deal', 'deal_seller_id', array(
             'fields' => 
             array(
              0 => 'seller_id',
             ),
             ));
        $this->removeIndex('deal', 'deal_store_id', array(
             'fields' => 
             array(
              0 => 'store_id',
             ),
             ));
    }
}