<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('store', 'trading_name', 'string', '255', array(
             ));
        $this->addColumn('store', 'address', 'string', '255', array(
             ));
        $this->addColumn('store', 'city', 'string', '255', array(
             ));
        $this->addColumn('store', 'province', 'string', '255', array(
             ));
        $this->addColumn('store', 'phone', 'string', '255', array(
             ));
        $this->addColumn('store', 'quarter', 'string', '255', array(
             ));
        $this->addColumn('store', 'email', 'string', '255', array(
             ));
        $this->addColumn('store', 'web', 'string', '255', array(
             ));
        $this->addColumn('store', 'salesman_and_position', 'string', '255', array(
             ));
        $this->addColumn('store', 'cuit', 'string', '255', array(
             ));
        $this->addColumn('store', 'condicion_iva', 'enum', '', array(
             'values' => 
             array(
              0 => 'RI',
              1 => 'Exento',
              2 => 'Monotributista',
             ),
             ));
        $this->addColumn('store', 'bank', 'string', '255', array(
             ));
        $this->addColumn('store', 'bank_account', 'string', '255', array(
             ));
        $this->addColumn('store', 'bank_cbu', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('store', 'trading_name');
        $this->removeColumn('store', 'address');
        $this->removeColumn('store', 'city');
        $this->removeColumn('store', 'province');
        $this->removeColumn('store', 'phone');
        $this->removeColumn('store', 'quarter');
        $this->removeColumn('store', 'email');
        $this->removeColumn('store', 'web');
        $this->removeColumn('store', 'salesman_and_position');
        $this->removeColumn('store', 'cuit');
        $this->removeColumn('store', 'condicion_iva');
        $this->removeColumn('store', 'bank');
        $this->removeColumn('store', 'bank_account');
        $this->removeColumn('store', 'bank_cbu');
    }
}