<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('store', 'store_quarter_id_quarter_id', array(
             'name' => 'store_quarter_id_quarter_id',
             'local' => 'quarter_id',
             'foreign' => 'id',
             'foreignTable' => 'quarter',
             ));
        $this->addIndex('store', 'store_quarter_id', array(
             'fields' => 
             array(
              0 => 'quarter_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('store', 'store_quarter_id_quarter_id');
        $this->removeIndex('store', 'store_quarter_id', array(
             'fields' => 
             array(
              0 => 'quarter_id',
             ),
             ));
    }
}