<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('deal', 'seller');
    }

    public function down()
    {
        $this->addColumn('deal', 'seller', 'string', '255', array(
             'notnull' => '1',
             ));
    }
}