<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('deal', 'deal_quarter_id_quarter_id', array(
             'name' => 'deal_quarter_id_quarter_id',
             'local' => 'quarter_id',
             'foreign' => 'id',
             'foreignTable' => 'quarter',
             ));
        $this->addIndex('deal', 'deal_quarter_id', array(
             'fields' => 
             array(
              0 => 'quarter_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('deal', 'deal_quarter_id_quarter_id');
        $this->removeIndex('deal', 'deal_quarter_id', array(
             'fields' => 
             array(
              0 => 'quarter_id',
             ),
             ));
    }
}