<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version29 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('deal', 'type');
        $this->removeColumn('store', 'quarter');
        $this->addColumn('deal', 'is_oferton', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('deal', 'has_yapa', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('deal', 'quarter_id', 'integer', '8', array(
             ));
        $this->addColumn('deal', 'max_per_buy', 'integer', '8', array(
             ));
        $this->addColumn('deal', 'max_deals', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('deal', 'type', 'string', '1', array(
             'notnull' => '1',
             ));
        $this->addColumn('store', 'quarter', 'string', '255', array(
             ));
        $this->removeColumn('deal', 'is_oferton');
        $this->removeColumn('deal', 'has_yapa');
        $this->removeColumn('deal', 'quarter_id');
        $this->removeColumn('deal', 'max_per_buy');
        $this->removeColumn('deal', 'max_deals');
    }
}