<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('deal', 'commission', 'integer', '8', array(
             ));
        $this->addColumn('deal', 'published_value', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('deal', 'commission');
        $this->removeColumn('deal', 'published_value');
    }
}