<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version35 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('newsletter_email', 'is_original', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->changeColumn('deal', 'seller_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('deal', 'store_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('deal', 'quarter_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('deal', 'commission', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('deal', 'offer', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('deal', 'published_value', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('deal', 'real_value', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('deal', 'newsletter_title', 'string', '50', array(
             'notnull' => '1',
             ));
        $this->changeColumn('newsletter_message', 'is_active', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('newsletter_email', 'is_original');
    }
}