<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version37 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('payment', 'dm_bought_on', 'timestamp', '25', array(
             ));
        $this->addColumn('payment', 'dm_id', 'string', '', array(
             ));
        $this->addColumn('payment', 'dm_amount', 'double', '', array(
             ));
        $this->addColumn('payment', 'dm_net_amount', 'double', '', array(
             ));
        $this->addColumn('payment', 'dm_method', 'integer', '8', array(
             ));
        $this->addColumn('payment', 'dm_medium', 'string', '', array(
             ));
        $this->addColumn('payment', 'dm_installments', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('payment', 'dm_bought_on');
        $this->removeColumn('payment', 'dm_id');
        $this->removeColumn('payment', 'dm_amount');
        $this->removeColumn('payment', 'dm_net_amount');
        $this->removeColumn('payment', 'dm_method');
        $this->removeColumn('payment', 'dm_medium');
        $this->removeColumn('payment', 'dm_installments');
    }
}