<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('payment', 'dm_buyer_email', 'string', '', array(
             ));
        $this->addColumn('payment', 'dm_buyer_address', 'string', '', array(
             ));
        $this->addColumn('payment', 'dm_buyer_comment', 'string', '', array(
             ));
        $this->addColumn('payment', 'dm_buyer_name', 'string', '', array(
             ));
        $this->addColumn('payment', 'dm_buyer_phone', 'string', '', array(
             ));
        $this->addColumn('payment', 'dm_buyer_tipodoc', 'string', '', array(
             ));
        $this->addColumn('payment', 'dm_buyer_numdoc', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('payment', 'dm_buyer_email');
        $this->removeColumn('payment', 'dm_buyer_address');
        $this->removeColumn('payment', 'dm_buyer_comment');
        $this->removeColumn('payment', 'dm_buyer_name');
        $this->removeColumn('payment', 'dm_buyer_phone');
        $this->removeColumn('payment', 'dm_buyer_tipodoc');
        $this->removeColumn('payment', 'dm_buyer_numdoc');
    }
}