generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Seller
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          seller
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing   #setting the css to a placeholder 

    config:
      actions: ~
      fields:
        first_name: { label: "Nombre" }
        last_name: { label: "Apellido" }
        phone: { label: "Teléfono" }
        cel_phone: { label: "Celular" }
        address: { label: "Domicilio" }
        percent: { label: "Porcentaje" }
      list:
        title: Listado de Vendedores
        display: [first_name, last_name]
      filter: 
        display: [first_name, last_name]

      form:    ~
      edit:
        title: Editar Vendedor
      
      new:
        title: Nuevo Vendedor
      
