detect_relations: true

Category:
  columns:
    name: { type: string(255), notnull: true, unique: true }
 

Quarter:
  columns:
    name: { type: string(255), notnull: true, unique: true }

Store:
  columns:
    name: { type: string(255), notnull: true, unique: true }
    trading_name: { type: string(255)}
    address: { type: string(255)}
    city: { type: string(255)}
    province: { type: string(255)}
    phone: { type: string(255)}
    quarter: { type: string(255)}
    quarter_id:  { type: integer}
    email: { type: string(255)}
    web: { type: string(255)}
    salesman_and_position: { type: string(255)}
    cuit: { type: string(255)}
    condicion_iva:
      type: enum
      values: [RI, Exento, Monotributista]]
    bank: { type: string(255)}
    bank_account: { type: string(255)}
    bank_cbu: { type: string(255)}


Seller:
  columns:
    first_name: { type: string(255), notnull: true }
    last_name: { type: string(255), notnull: true}
    phone: { type: string(255), notnull: true}
    cel_phone: { type: string(255), notnull: true}
    address: { type: string(255), notnull: true}
    percent:   { type: integer, notnull: true }

Deal:
  actAs: { Timestampable: ~ }
  columns:
    type:         { type: string(1), notnull: true }
    category_id:  { type: integer }
    seller_id:  { type: integer}
    store_id:  { type: integer}
    starts_at:   { type: timestamp, notnull: true }
    ends_at:   { type: timestamp, notnull: true }
    bought_count:   { type: integer, notnull: true }
    visited_count:   { type: integer, notnull: true }
    printed_count:   { type: integer, notnull: true }
    offer:  integer
    real_value:  integer
    image:  { type: string(255) }
    title:  { type: string(255), notnull: true }
    newsletter_title:  { type: string(50) }
    featured: { type: string(4000), notnull: true }
    conditions: { type: string(4000), notnull: true }
    description:  { type: string(4000), notnull: true }



Payment:
  actAs: { Timestampable: ~ }
  columns:
    status:  { type: string(1), notnull: true }
    deal_id: { type: integer, notnull: true }
    user_id: { type: integer, notnull: true }
    quantity:   { type: integer, notnull: true }
    price:   { type: integer, notnull: true }
    offer:   { type: integer, notnull: true }
    real_value:   { type: integer, notnull: true }
    saved:   { type: integer, notnull: true }
    code: integer
  relations:
    sfGuardUser:
      alias: User
      foreign: id
#      foreignAlias: Payments
      foreignType: many
      local: user_id
      onDelete: CASCADE
      
NewsletterEmail:
  columns:
    email:
      type: string(255)
      notnull: true
      unique: true
    is_active:
      type: boolean
      default: 1

NewsletterMessage:
  actAs: { Timestampable: ~ }
  columns:
    from_email:  { type: string(255), notnull: true }
    from_name:  { type: string(255), notnull: true }
    subject:  { type: string(255), notnull: true }
    body: { type: string(4000), notnull: true }
    limit_i:   { type: integer, notnull: true }
    offset_i:   { type: integer, notnull: true }
    recipients_count:   { type: integer, notnull: true }
    sent_count:   { type: integer, notnull: true }
    is_active: { type: boolean}
      
